FROM ubuntu:latest

RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y sudo vim unzip nano htop wget net-tools python3 python3-pip

RUN pip3 install jupyterlab 
RUN jupyter lab --generate-config

RUN apt-get update
RUN pip3 install "jupyterlab-kite>=2.0.2"
RUN pip install --upgrade jupyterlab jupyterlab-git

WORKDIR /home

CMD ["jupyter","lab","--ip=0.0.0.0","--port=8888","--allow-root"]